const users = [
    {
        id: "1001",
        ownerName: "Maggie",
        dogName: "Bruno", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-MAGGIE.jpg",
        location: "Quebec City",  
        joined:"July 18, 2019", 
        playdates: [{"requested-by":"ahg4@notgamil.com", "status":"pending"}],
        email: "fb2et@notgamil.com",
    }, 
    {
        id: "1002",
        ownerName: "Gina",
        dogName: "Frankie", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-GINA.jpg",
        location: "Laval", 
        joined:"January 21, 2021",
        playdates: [{"requested-by":"fb2et@notgamil.com", "status":"pending"},{"requested-by":"g89@notgamil.com", "status":"pending"}],
        email:"ahg4@notgamil.com",
    }, 
    {
        id: "1003",
        ownerName: "Taylor",
        dogName: "Dixie", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-TAYLOR.jpg",
        location: "Quebec City", 
        joined:"February 26, 2022",
        playdates: [{"requested-by":"m9dh@notgamil.com", "status":"pending"},{"requested-by":"g89@notgamil.com", "status":"pending"}],
        email: "g89@notgamil.com", 
    }, 
    {
        id: "1004",
        ownerName: "Marc",
        dogName: "Oreo", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-MARC.jpg",
        location: "Montréal", 
        joined:"January 20, 2019", 
        playdates: [{"requested-by":"kenziecard@gmail.com", "status":"pending"}],
        email: "mo21@notgamil.com", 
    },
    {
        id: "1005",
        ownerName: "Casey",
        dogName: "Harley", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-CASEY.jpg",
        location: "Dorval", 
        joined:"April 26, 2021",
        playdates: [{"requested-by":"ejue9@notgamil.com", "status":"pending"},{"requested-by":"g89@notgamil.com", "status":"pending"}],
        email: "m9dh@notgamil.com", 
    },
    {
        id: "1006",
        ownerName: "Drew",
        dogName: "Finn", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-DREW.jpg",
        location: "Montréal", 
        joined:"April 26, 2021", 
        playdates: [{"requested-by":"mo21@notgamil.com", "status":"pending"}],
        email: "ejue9@notgamil.com", 
    },
    {
        id: "1007",
        ownerName: "Jason",
        dogName: "Coco", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-JASON.jpg",
        location: "Montréal", 
        joined:"January 27, 2019", 
        playdates: [{"requested-by":"kenziecard@gmail.com", "status":"pending"}, {"requested-by":"57shga@notgamil.com", "status":"pending"}],
        email: "ght89@notgamil.com", 
    },
    {
        id: "1008",
        ownerName: "Derek",
        dogName: "Boston", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-DEREK.jpg",
        location: "Montréal", 
        joined:"July 17, 2021",
        playdates: [{"requested-by":"57shga@notgamil.com", "status":"pending"}], 
        email: "9dhsgf@notgamil.com", 
    },
    {
        id: "1009",
        ownerName: "Nicole",
        dogName: "Zeus", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-NICOLE.jpg",
        location: "Montréal", 
        joined:"October 14, 2018", 
        playdates: [{"requested-by":"kenziecard@gmail.com", "status":"pending"},{"requested-by": "57shga@notgamil.com", "status":"pending"}],
        email: "mab384@notgamil.com", 
    },
    {
        id: "1010",
        ownerName: "Florence",
        dogName: "Minnie", 
        avatarSrc: "/assets/profile-pics/PROJECT-PIC-FLORENCE.jpg",
        location: "Montréal", 
        joined:"January 11, 2022", 
        playdates: [{"requested-by":"kenziecard@gmail.com", "status":"pending"}],
        email: "57shga@notgamil.com", 
    },
]; 

module.exports = {users}